### ISSUE TITLE
Feature: Mutliple Ascom Remote Servers

### ISSUE THREAD

**Issue by robbrad** [mawinkler/astrolive#1]
Is it possible to have multiple Ascome Remote Servers? 

I have a mini PC on each of my scopes and one for the observatory - could Ascome Live support more than one Ascome Remote server?

**Comment by mawinkler** [comment]
Currently it's one astrolive instance per ascom remote. If you're using it running as a container multiple instances are easily possible. Just map a different config file to each instance.

**Comment by robbrad** [comment]
Yeh good idea ! Thanks and great work on this project
