### ISSUE TITLE
docker-compose error when starting the container

### ISSUE THREAD

**Issue by LeorFinacre** [mawinkler/astrolive#23]
Hello !

I'm trying to get my hand on this wonderful project.
I have already lots of docker sub applications for my home assistant instance (mqtt, zigbeetomqtt, esphome etc ...) under /home/homeassistant/addons folder on my raspi 4.

I'm naturally trying to install astrolive in a separate folder inside /home/homeassistant/addons
Inside it, i'm creating a file named docker-compose.yml with the following content : 

```yaml
version: "3.2"
services:
  astrolive:
    image: astrolive:latest
    container_name: astrolive
    #depends_on:
      #- mqtt
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /home/homeassistant/addons/astrolive/default.cfg.yaml:/usr/src/app/astrolive/default.cfg.yaml
      - /fits:/fits:ro
    restart: always
```

I had to comment the depends_on section cause it was always failing to create the container, it doesn't know the mqtt dependency.

I also have created the /addons/astrolive/default.cfg.yaml file.
But when I start the container with _sudo docker-compose up_ command, I get this error in the log : 

```log
░█████╗░░██████╗████████╗██████╗░░█████╗░██╗░░░░░██╗██╗░░░██╗███████╗
██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██║░░░░░██║██║░░░██║██╔════╝
███████║╚█████╗░░░░██║░░░██████╔╝██║░░██║██║░░░░░██║╚██╗░██╔╝█████╗░░
██╔══██║░╚═══██╗░░░██║░░░██╔══██╗██║░░██║██║░░░░░██║░╚████╔╝░██╔══╝░░
██║░░██║██████╔╝░░░██║░░░██║░░██║╚█████╔╝███████╗██║░░╚██╔╝░░███████╗
╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░╚════╝░╚══════╝╚═╝░░░╚═╝░░░╚══════╝
2024-09-03 11:29:09 INFO (MainThread) [read_config] Loading configuration from: /app/astrolive/default.cfg.yaml
2024-09-03 11:29:09 INFO (MainThread) [read_config] Non existing config file: /root/astrolive.cfg.yaml
2024-09-03 11:29:09 INFO (MainThread) [read_config] Non existing config file: ./astrolive.cfg.yaml
Traceback (most recent call last):
  File "/app/run.py", line 64, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/run.py", line 46, in main
    al = AstroLive()
         ^^^^^^^^^^^
  File "/app/astrolive/client.py", line 60, in __init__
    configuration = Config.global_instance()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/astrolive/config.py", line 50, in global_instance
    cls.global_instance_from_files()
  File "/app/astrolive/config.py", line 64, in global_instance_from_files
    cls._singleton = cls.instance_from_files(source=source)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/astrolive/config.py", line 78, in instance_from_files
    cfg.read_config(source=source)
  File "/app/astrolive/config.py", line 104, in read_config
    self.expand_includes(config, config_keys)
  File "/app/astrolive/config.py", line 128, in expand_includes
    config_dict[key].update(config_dict[i])
                            ~~~~~~~~~~~^^^
KeyError: 'travel'
```

From what I understand, it does not load my config file and therefore load the default one ?
I can't figure out how to resolve this.

If someone has something in mind, please share ! 

Leor

**Comment by mawinkler** [comment]
So, a couple of things:

1. The example of the service definition for AstroLive assumes that it is in the same docker-compose file as the service definition of the mqtt service. This is probably the reason why this dependency does not work for you. Setting this dependency is not mandatory, but the mqtt service should be reachable from AstroLive.
2. You pointed out a historical error in the README.md. Thanks for that. The location of the config file inside the container should be `/app/astrolive/default.cfg.yaml`, so without `/usr/src`. I have already corrected this.
3. Advice: Don't run docker as root (with sudo). Put your unprivileged user in the docker group instead :-)

But thanks for reporting the documentation bug!

**Comment by LeorFinacre** [comment]
Thank's a lot for the answer and the tips for docker user ! 
I was able to run it with your response.

Keep up the good work :)
