### ISSUE TITLE
Issue with FITS file - type str doesn't define __round__ method

### ISSUE THREAD

**Issue by zdesignstudio** [mawinkler/astrolive#4]
Hello,

Everything works fine except I am getting this error with the camera_file component.

2023-10-10 02:32:13 INFO (MainThread) [start_monitoring] Thread obs.telescope.camera_file started
2023-10-10 02:32:13 INFO (obs.telescope.camera_file) [_publish_camera_file] obs.telescope.camera_file: Reading image /fits/test.fits
2023-10-10 02:32:13 ERROR (obs.telescope.camera_file) [_publish_camera_file] type str doesn't define __round__ method
Exception in thread obs.telescope.camera_file:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/astrolive/astrolive/mqttdevices.py", line 532, in publish_loop
    await self._publish_camera_file(sys_id, device, device_type, execution_time)
  File "/astrolive/astrolive/mqttdevices.py", line 694, in _publish_camera_file
    raise exc
  File "/astrolive/astrolive/mqttdevices.py", line 660, in _publish_camera_file
    "ra_of_imaged_object": round(hdr.get("OBJCTRA", 0), 3),
TypeError: type str doesn't define __round__ method

**Comment by zdesignstudio** [comment]
I confirmed the FITS file correctly contains the header.

    OBJCTRA = '06 32 06'           / [H M S] RA of imaged object
    OBJCTDEC= '+04 58 18'          / [D M S] Declination of imaged object

**Comment by zdesignstudio** [comment]
So I narrowed it down to being the round() operation and it does it with both the OBJCTRA and OBJCTDEC.  It does not like the  format it is in. I removed the round() from the YAML and left it with only the hdr.get("OBJCTRA", 0) and that processes just fine and I see that information being pushed out via MQTT. I guess I will leave it like that for now until I decide to figure out how to convert that string.

**Comment by zdesignstudio** [comment]
I was able to make the conversion from hms/dms to degrees and send it out via MQTT.

First add the dependencies
`from astropy.coordinates import SkyCoord # High-level coordinates
from astropy.coordinates import Angle # Angles`

Then add the section to pull the data from the FITS header and do the conversion under the publish_camera_file definition above the mqtt topic.
`                
            **OBJCTRA_FITS = hdul[0].header['OBJCTRA']
            OBJCTDEC_FITS = hdul[0].header['OBJCTDEC']
            COORDS = SkyCoord(OBJCTRA_FITS, OBJCTDEC_FITS, unit=(u.hour, u.deg))**
            
            topic = "astrolive/" + device_type + "/" + sys_id_ + "/"
            try:
                await self._publisher.publish_mqtt(topic + "lwt", "ON")
               `

Then update the mqtt publish topics

`                    "object_of_interest": hdr.get("OBJECT", "n/a"),
                    **"ra_of_imaged_object": COORDS.ra.degree,
                    "declination_of_imaged_object": COORDS.dec.degree,**
                    "rotation_of_imaged_object": round(hdr.get("OBJCTROT", 0), 3),`

**Comment by zdesignstudio** [comment]
I was able to make the conversion from hms/dms to degrees and send it out via MQTT.

First add the dependencies

     from astropy.coordinates import SkyCoord # High-level coordinates
     from astropy.coordinates import Angle # Angles


Then add the section to pull the data from the FITS header and do the conversion under the publish_camera_file definition above the mqtt topic.


     OBJCTRA_FITS = hdul[0].header['OBJCTRA']
     OBJCTDEC_FITS = hdul[0].header['OBJCTDEC']
     COORDS = SkyCoord(OBJCTRA_FITS, OBJCTDEC_FITS, unit=(u.hour, u.deg))

     topic = "astrolive/" + device_type + "/" + sys_id_ + "/"

Then update the mqtt publish topics

    "ra_of_imaged_object": COORDS.ra.degree,
    "declination_of_imaged_object": COORDS.dec.degree,


That will convert them and show as degree in HA.

Here is a FITS preview of the header data that I am pulling from in the hms / dms format.
![image](https://github.com/mawinkler/astrolive/assets/36992940/5d9b437f-70fd-41c5-ba96-752838ecde9f)

Here it is converted to degree in HA.
![image](https://github.com/mawinkler/astrolive/assets/36992940/d62925c9-35cb-4aff-80fc-1289be2b81ce)

**Comment by mawinkler** [comment]
Thank you for this. I also stumbled across this a few days ago but didn't find the time to fix it. I'm curious what changed since it worked until recently.
I need to spend some time on the entity naming since there are some changes coming in Home Assistant.

**Comment by mawinkler** [comment]
Fixed in [v0.5](https://github.com/mawinkler/astrolive/releases/tag/v0.5)

**Comment by zdesignstudio** [comment]
> Thank you for this. I also stumbled across this a few days ago but didn't find the time to fix it. I'm curious what changed since it worked until recently. I need to spend some time on the entity naming since there are some changes coming in Home Assistant.

Anytime. Let me know if you need anything.
